import blast_dev

SSEQ = "TTAGCCAGTGAGGGAATATTGGTCAATGGTCTAAGGACTGAACCAGCAATTTGGAGGAATGAAAAACGAATAAGTCGTATAAAGTTCTAGATAAAAAATTTATAATGACTAATTTTTATCTATAAGTCTTGACCAAATTACGTGCCAGCAGTCGCGGTAATACGTAGAAGACAAGTGTTATTCATCTTTAACAGGTTTAAAGGGTACCTAGACGGAAAATCAAGCCATAGAAGGGACTAATTTTCTAGAGTTTTATGTGTGAAGATCGAATGACCTGAAGAGCAATAAAATGCATTGACACAGGGAAGACGGGTAGCGGCGAAGGCAATCTTCTATGTAGAAACTGACGTTGAGGGACGAAGCCTTGGGGAGCGAGAAGGATTAGATACCCTAGTAGTCCTTGGAGAAAATTATGAGTGCCATAGACTAGGTACTAGTTTATAAATGAAAGTGTAAGCATTCCACCTCATGAGTAAAGCGGCAACGCCGAAATTGAAATCATTAGACCGTATCTGAAACCAGTAGTGAAGTATGTTATTTAATTCGATGGTCCGCGAATAACCTTACCACCTCTTGAATATTTTTACAAGCGCTGCACGGCTGTCTTCAGTTAATGTCGTGAGATTTTGGTTTGTTCCATTAATTAACGAAAACCCATGTTTTATTTTTATATATAAAGCAGTTCACCGTTATATTGGATAAGATAAACGGGATCAAGACAAGTCATTCATGGGCTTAATGAGTGTGGGCTATAGACGTGCCACATAGGGGAGAAC"
SSAV = "testmode.txt"

def single_test():
    b = blast_dev.NCBI_search(seq=SSEQ, savename=SSAV)
    b.process()
    b.process()
    print(b.info)

def small_batch():
    b = blast_dev.batch_search('3.fasta', interval=15, loop_interval=60)
    # b.process()

def big_batch():
    b = blast_dev.batch_search('97_documents_from_BT3剪切.fasta', interval=15, loop_interval=60)
    b.process()

big_batch()